import Head from 'next/head';
import Header from '@/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={inter.className}>
         <>
           <Head>
            <tittle>Replica de spotify</tittle>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
           </Head>

             <div className='bg-spotify-gray min-h-screen text-gray-300'>
               <Header />
               <Sidebar />
      
                <main>
                   {children}
                </main>

             </div>
         </>
       </body>
    </html>
  )
}
